// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rezerv.Payroll.Infrastructure.Persistence;

#nullable disable

namespace Rezerv.Payroll.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PayrollDbContext))]
    [Migration("20261008095514_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Rezerv.Payroll.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId", "Status");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("Rezerv.Payroll.Domain.Entities.Instructor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("StudioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("StudioId");

                    b.ToTable("instructors", (string)null);
                });

            modelBuilder.Entity("Rezerv.Payroll.Domain.Entities.ManualAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId", "EffectiveDate");

                    b.ToTable("manual_adjustments", (string)null);
                });

            modelBuilder.Entity("Rezerv.Payroll.Domain.Entities.PayrollClassLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AttendedBookings")
                        .HasColumnType("int");

                    b.Property<decimal>("BonusEarned")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("BookingEarnings")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("CancelledBookings")
                        .HasColumnType("int");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<decimal>("FixedFee")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("FixedFeeEarned")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("NoShowBookings")
                        .HasColumnType("int");

                    b.Property<int>("PayableBookings")
                        .HasColumnType("int");

                    b.Property<Guid>("PayrollEntryId")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("PerBookingPayout")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("UnpaidNoShowBookings")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PayrollEntryId");

                    b.ToTable("payroll_class_lines", (string)null);
                });

            modelBuilder.Entity("Rezerv.Payroll.Domain.Entities.PayrollEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Adjustment")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("Bonus")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("BookingEarnings")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("ClassesCancelled")
                        .HasColumnType("int");

                    b.Property<int>("ClassesCompleted")
                        .HasColumnType("int");

                    b.Property<decimal>("Commission")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<decimal>("FinalPayout")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("FixedClassEarnings")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("InstructorName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("NoShowPayoutPolicyApplied")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("PayableBookings")
                        .HasColumnType("int");

                    b.Property<Guid>("PayrollRunId")
                        .HasColumnType("char(36)");

                    b.Property<string>("StudioName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("UnpaidNoShowBookings")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.HasIndex("PayrollRunId", "InstructorId")
                        .IsUnique();

                    b.ToTable("payroll_entries", (string)null);
                });

            modelBuilder.Entity("Rezerv.Payroll.Domain.Entities.PayrollLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateOnly>("OccurredOn")
                        .HasColumnType("date");

                    b.Property<Guid>("PayrollEntryId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("Rate")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<decimal?>("UnitAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("PayrollEntryId");

                    b.HasIndex("ReferenceType", "ReferenceId");

                    b.ToTable("payroll_line_items", (string)null);
                });

            modelBuilder.Entity("Rezerv.Payroll.Domain.Entities.PayrollRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("StartDate", "EndDate")
                        .IsUnique()
                        .HasDatabaseName("ux_payroll_runs_period");

                    b.ToTable("payroll_runs", (string)null);
                });

            modelBuilder.Entity("Rezerv.Payroll.Domain.Entities.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("RefundedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("SoldAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("StudioId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("RefundedAt");

                    b.HasIndex("StudioId");

                    b.HasIndex("InstructorId", "SoldAt");

                    b.ToTable("sales", (string)null);
                });

            modelBuilder.Entity("Rezerv.Payroll.Domain.Entities.Studio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("AttendanceBonusAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("AttendanceBonusThreshold")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<decimal>("MembershipCommissionRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("NoShowPayoutPolicy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<decimal>("PackageCommissionRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.HasKey("Id");

                    b.ToTable("studios", (string)null);
                });

            modelBuilder.Entity("Rezerv.Payroll.Domain.Entities.StudioClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<decimal>("FixedFee")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<decimal?>("PerBookingPayout")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<Guid>("StudioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("StartsAt");

                    b.HasIndex("StudioId");

                    b.HasIndex("InstructorId", "StartsAt");

                    b.ToTable("classes", (string)null);
                });

            modelBuilder.Entity("Rezerv.Payroll.Domain.Entities.Booking", b =>
                {
                    b.HasOne("Rezerv.Payroll.Domain.Entities.StudioClass", "Class")
                        .WithMany("Bookings")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("Rezerv.Payroll.Domain.Entities.Instructor", b =>
                {
                    b.HasOne("Rezerv.Payroll.Domain.Entities.Studio", "Studio")
                        .WithMany("Instructors")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("Rezerv.Payroll.Domain.Entities.ManualAdjustment", b =>
                {
                    b.HasOne("Rezerv.Payroll.Domain.Entities.Instructor", "Instructor")
                        .WithMany("ManualAdjustments")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Rezerv.Payroll.Domain.Entities.PayrollClassLine", b =>
                {
                    b.HasOne("Rezerv.Payroll.Domain.Entities.PayrollEntry", "PayrollEntry")
                        .WithMany("ClassLines")
                        .HasForeignKey("PayrollEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PayrollEntry");
                });

            modelBuilder.Entity("Rezerv.Payroll.Domain.Entities.PayrollEntry", b =>
                {
                    b.HasOne("Rezerv.Payroll.Domain.Entities.Instructor", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Rezerv.Payroll.Domain.Entities.PayrollRun", "PayrollRun")
                        .WithMany("Entries")
                        .HasForeignKey("PayrollRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");

                    b.Navigation("PayrollRun");
                });

            modelBuilder.Entity("Rezerv.Payroll.Domain.Entities.PayrollLineItem", b =>
                {
                    b.HasOne("Rezerv.Payroll.Domain.Entities.PayrollEntry", "PayrollEntry")
                        .WithMany("LineItems")
                        .HasForeignKey("PayrollEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PayrollEntry");
                });

            modelBuilder.Entity("Rezerv.Payroll.Domain.Entities.Sale", b =>
                {
                    b.HasOne("Rezerv.Payroll.Domain.Entities.Instructor", "Instructor")
                        .WithMany("Sales")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Rezerv.Payroll.Domain.Entities.Studio", "Studio")
                        .WithMany()
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instructor");

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("Rezerv.Payroll.Domain.Entities.StudioClass", b =>
                {
                    b.HasOne("Rezerv.Payroll.Domain.Entities.Instructor", "Instructor")
                        .WithMany("Classes")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Rezerv.Payroll.Domain.Entities.Studio", "Studio")
                        .WithMany()
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instructor");

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("Rezerv.Payroll.Domain.Entities.Instructor", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("ManualAdjustments");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Rezerv.Payroll.Domain.Entities.PayrollEntry", b =>
                {
                    b.Navigation("ClassLines");

                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("Rezerv.Payroll.Domain.Entities.PayrollRun", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Rezerv.Payroll.Domain.Entities.Studio", b =>
                {
                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("Rezerv.Payroll.Domain.Entities.StudioClass", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
